warn when using nested ternary
GrowflowTeam/javascript pull request #10
Opened 2022-03-25 20:48 UTC by dwheale

2022-03-25 20:49 UTC, dwheale commented
This will suggest engineers write code that is easier to read and more maintainable.

2022-03-25 20:52 UTC, chadly requested changes

2022-03-25 20:52 UTC, chadly commented on packages/eslint/core.js
>      // who doesn't love a good nested ternary?
you have to change the snarky comment, too 😉

2022-03-25 20:52 UTC, chadly commented on packages/eslint/core.js
> +    'unicorn/no-nested-ternary': 'warn',
I'm more of a type-a personality. Should we go "all the way" with `error` instead?

2022-03-28 13:14 UTC, chadly commented on packages/eslint/core.js
> +    'unicorn/no-nested-ternary': 'warn',
nah, after sleeping on it, it seems better as a "suggestion" / warning like you did here

2022-03-28 13:15 UTC, chadly commented on packages/eslint/core.js
>      // who doesn't love a good nested ternary?
actually, I think the comment still makes sense since it's transitioned to warn, not error

2022-03-28 13:15 UTC, chadly approved these changes

2022-03-28 13:16 UTC, merged